name: Build and Upload Coverage

on:
  push:
    branches:
      - "**"
  pull_request:

  workflow_dispatch:

jobs:
  coverage:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          arch: win64_msvc2019_64

      - name: Install OpenCppCoverage
        shell: powershell
        run: |
          choco install opencppcoverage -y

      - name: Configure CMake
        shell: cmd
        run: >
          cmake -S . -B build
          -G "Visual Studio 16 2019"
          -A x64
          -DCMAKE_PREFIX_PATH="%Qt5_DIR%"

      - name: Build
        shell: cmd
        run: cmake --build build --config Debug

      - name: Generate Coverage
        shell: cmd
        run: >
          "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe"
          --export_type=cobertura:build\coverage.xml
          --timeout 15
          --
          build\Debug\Jogo.exe

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/coverage.xml
          fail_ci_if_error: true